/** @format */

var uiTxtScreen = document.getElementById("text-screen");
var brandingTxtScreen = document.getElementById("text-screen2");

let uiArray = [
 "Design a mobile app for a restaurant",
  "Create a website for a non-profit organization",
  "Redesign a popular e-commerce website",
  "Design a booking platform for travel accommodation",
  "Create a dashboard for a data visualization tool",
  "Design a messaging app for a specific target audience",
  "Redesign the user interface for a social media platform",
  "Create an online education platform",
  "Design a calendar app for productivity",
  "Create a chatbot for customer support",
  "Redesign the user interface for a fitness app",
  "Design an e-commerce platform for luxury goods",
  "Create a weather app with personalized features",
  "Design an online voting platform",
  "Redesign a transportation app for a major city",
  "Create a recipe-sharing platform",
  "Design a job search website for a specific industry",
  "Create a task management app for remote teams",
  "Design a music streaming platform",
  "Redesign the user interface for a budgeting app",
  "Create an online marketplace for handmade goods",
  "Design a news aggregator website or app",
  "Create a personalized shopping assistant",
  "Design a social network for a specific hobby or interest",
  "Redesign the user interface for a healthcare app",
  "Create a productivity app for students",
  "Design an online portfolio platform for creatives",
  "Create a habit-tracking app",
  "Design a fashion e-commerce platform",
  "Redesign the user interface for a mobile banking app",
  "Create an online fitness class platform",
  "Design a travel planning app",
  "Create a language learning app",
  "Design an event planning platform",
  "Redesign the user interface for a weather app",
  "Create a mental health app",
  "Design a ride-sharing app",
  "Create a tool for managing personal finances",
  "Design an augmented reality experience",
  "Redesign the user interface for a podcast app",
  "Create an online art gallery",
  "Design a meditation app",
  "Create an app for finding and booking fitness classes",
  "Design a real estate search platform",
  "Redesign the user interface for a personal assistant app",
  "Create a virtual wardrobe app",
  "Design a delivery service app",
  "Create a time management tool",
  "Design a fashion rental platform",
  "Redesign the user interface for a shopping app",
  "Create an online support community for a specific health condition",
  "Design a social impact platform for volunteering and activism"
];

let project = Math.floor(Math.random() * uiArray.length);

uiTxtScreen.innerHTML = uiArray[project];

let brandingArray = [
 "Design a logo for a new business in a specific industry",
  "Create a brand identity for a boutique hotel",
  "Design packaging for a new line of health food products",
  "Create a brand guide for a non-profit organization",
  "Design a website for a craft brewery",
  "Create a brand identity for a beauty salon",
  "Design packaging for a line of artisanal candles",
  "Create a brand guide for a tech startup",
  "Design a logo for a new line of athletic wear",
  "Create a brand identity for a high-end jewelry store",
  "Design packaging for a line of eco-friendly cleaning products",
  "Create a brand guide for a food delivery app",
  "Design a logo for a new coffee shop",
  "Create a brand identity for a music festival",
  "Design packaging for a line of organic skincare products",
  "Create a brand guide for a fashion e-commerce platform",
  "Design a logo for a new co-working space",
  "Create a brand identity for a luxury car brand",
  "Design packaging for a line of premium pet food products",
  "Create a brand guide for a travel booking website",
  "Design a logo for a new line of gourmet snacks",
  "Create a brand identity for a financial services firm",
  "Design packaging for a line of premium chocolates",
  "Create a brand guide for a wellness app",
  "Design a logo for a new restaurant",
  "Create a brand identity for a book publisher",
  "Design packaging for a line of organic baby products",
  "Create a brand guide for a digital marketing agency",
  "Design a logo for a new online marketplace",
  "Create a brand identity for a design studio",
  "Design packaging for a line of artisanal teas",
  "Create a brand guide for a social media platform",
  "Design a logo for a new fitness studio",
  "Create a brand identity for a medical practice",
  "Design packaging for a line of eco-friendly household products",
  "Create a brand guide for a virtual event platform",
  "Design a logo for a new real estate agency",
  "Create a brand identity for a furniture store",
  "Design packaging for a line of gourmet popcorn",
  "Create a brand guide for a sports apparel brand",
  "Design a logo for a new home goods store",
  "Create a brand identity for a dance school",
  "Design packaging for a line of premium coffee",
  "Create a brand guide for a crowdfunding platform",
  "Design a logo for a new music streaming service",
  "Create a brand identity for a travel agency",
  "Design packaging for a line of luxury chocolates",
  "Create a brand guide for an educational technology company",
  "Design a logo for a new pet store",
  "Create a brand identity for a photography business",
  "Design packaging for a line of premium spices",
  "Create a brand guide for a language learning app"
];
let project2 = Math.floor(Math.random() * brandingArray.length);

brandingTxtScreen.innerHTML = brandingArray[project2];
